"""create houses table

Revision ID: 74fe91afd964
Revises: 
Create Date: 2025-08-05 16:43:50.301121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74fe91afd964'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('area', sa.Integer(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('bathroom', sa.Integer(), nullable=True),
    sa.Column('parking_spaces', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('animal', sa.Integer(), nullable=True),
    sa.Column('furniture', sa.Integer(), nullable=True),
    sa.Column('hoa', sa.Integer(), nullable=True),
    sa.Column('rent_amount', sa.Integer(), nullable=True),
    sa.Column('property_tax', sa.Integer(), nullable=True),
    sa.Column('fire_insurance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_houses_animal'), 'houses', ['animal'], unique=False)
    op.create_index(op.f('ix_houses_furniture'), 'houses', ['furniture'], unique=False)
    op.create_index(op.f('ix_houses_id'), 'houses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_houses_id'), table_name='houses')
    op.drop_index(op.f('ix_houses_furniture'), table_name='houses')
    op.drop_index(op.f('ix_houses_animal'), table_name='houses')
    op.drop_table('houses')
    # ### end Alembic commands ###
